name: flutter_state_management
description: Flutter State Management Vanilla,Provider,MobX,Bloc

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #State
  provider: ^6.0.4
  flutter_mobx: ^2.0.6+5
  flutter_bloc: ^8.1.1

  #Utility
  kartal: ^2.5.1

  #Google
  google_maps_flutter: ^2.2.1
  json_serializable: ^6.5.4
  json_annotation: ^4.7.0

  #Core
  vexana: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  mobx_codegen: ^2.1.1

flutter:


  uses-material-design: true

 
  assets:
    - asset/images/
    - asset/images/feed/
